---
name: Build MCP Dependencies Image

on:
  push:
    branches:
      - main
    paths:
      - 'mcp-dependencies-image/**'
      - 'mcp-server/requirements.txt'
  workflow_dispatch:

jobs:

  validate_new_version:
    name: Validate new version
    runs-on: ubuntu-latest
    outputs:
      planned_version: ${{ steps.validate_new_version.outputs.planned_version }}
      version_file_exists: ${{ steps.validate_new_version.outputs.version_file_exists }}
      tag_hash: ${{ steps.validate_new_version.outputs.tag_hash }}
      can_create: ${{ steps.validate_new_version.outputs.can_create }}
      tag_exists: ${{ steps.validate_new_version.outputs.tag_exists }}
      branch_name: ${{ steps.validate_new_version.outputs.branch_name }}

    steps:

      - name: Check out this repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Workaround the version file format
        id: prepare_version_file
        shell: bash
        run: >-
          grep __version__ mcp-dependencies-image/version.py | cut -d "=" -f 2 | tr -d "'\" " > .version

      - name: Use latest released action
        id: validate_new_version
        uses: reinvented-stuff/validate-version-action@1.2.0
        with:
          version_filename: ".version"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          fail_on_error: true


  docker_image:
    name: Build Docker image
    outputs:
      job_status: ${{ job.status }}
    runs-on: ubuntu-latest

    needs:
      - validate_new_version

    env:
      PLANNED_VERSION: ${{ needs.validate_new_version.outputs.planned_version }}
      TAG_HASH: ${{ needs.validate_new_version.outputs.tag_hash }}
      CAN_CREATE_RELEASE: ${{ needs.validate_new_version.outputs.can_create }}
      TAG_EXISTS: ${{ needs.validate_new_version.outputs.tag_exists }}
      BRANCH_NAME: ${{ needs.validate_new_version.outputs.branch_name }}
      APP_NAME: "mcp-dependencies-image"

    steps:

      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push deps image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: mcp-dependencies-image/Dockerfile
          push: ${{ env.CAN_CREATE_RELEASE == 'true' }}
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${{ env.PLANNED_VERSION }}
            ghcr.io/${{ github.repository }}/${{ env.APP_NAME }}:${{ env.TAG_HASH }}
          build-args: |
            APP_VERSION=${{ env.PLANNED_VERSION }}
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}

...
